version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    ports:
      - "3000:3000"

  scheduler:
    build: .
    container_name: python_scheduler
    volumes:
      - .:/app
    working_dir: /app
    command: python scheduler.py